# Generated by Django 3.2.5 on 2022-08-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='tapa_libro',
            field=models.ImageField(blank=True, null=True, upload_to='catalogo/%Y/%m/%d'),
        ),
    ]
